In [68]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [69]:
RANDOM_STATE = 67

df = pd.read_pickle("./filtered_data.pkl")
df["outcome"] = (df["outcome_name"] == "Goal").astype(int)
df

outcome_name  under_pressure sub_type_name body_part_name  \
0          Blocked             NaN     Open Play     Right Foot   
1          Blocked             NaN     Open Play     Right Foot   
2            Off T             1.0     Open Play      Left Foot   
3            Off T             NaN     Open Play           Head   
4          Wayward             NaN     Open Play     Right Foot   
...            ...             ...           ...            ...   
19811        Saved             NaN     Open Play     Right Foot   
19812        Saved             NaN     Open Play     Right Foot   
19813      Blocked             NaN     Open Play     Right Foot   
19814        Saved             NaN     Open Play      Left Foot   
19815        Saved             NaN     Open Play     Right Foot   

      shot_first_time      x     y pass_deflected shot_one_on_one  \
0                 NaN  107.1  26.6            NaN             NaN   
1                 NaN  113.7  54.0            NaN             NaN   
2                True  115.7  50.5            NaN             NaN   
3                 NaN  113.9  38.6            NaN             NaN   
4                 NaN   96.7  47.2            NaN             NaN   
...               ...    ...   ...            ...             ...   
19811             NaN  109.1  29.8            NaN             NaN   
19812             NaN  114.6  51.4            NaN            True   
19813             NaN   98.3  56.9            NaN             NaN   
19814             NaN  102.9  58.1            NaN             NaN   
19815             NaN   99.9  37.4            NaN             NaN   

      play_pattern_name type_name goalkeeper_position_name technique_name  \
0          Regular Play      Shot                      NaN         Normal   
1          Regular Play      Shot                      NaN         Normal   
2          Regular Play      Shot                      NaN  Overhead Kick   
3         From Throw In      Shot                      NaN         Normal   
4        From Free Kick      Shot                      NaN    Half Volley   
...                 ...       ...                      ...            ...   
19811      Regular Play      Shot                      NaN         Normal   
19812      From Counter      Shot                      NaN         Normal   
19813     From Throw In      Shot                      NaN         Normal   
19814      Regular Play      Shot                      NaN         Normal   
19815      Regular Play      Shot                      NaN         Normal   

       distance_to_goal  angle_to_goal  outcome  
0             18.600269      15.850859        0  
1             15.352199      11.720028        0  
2             11.346365      15.263642        0  
3              6.258594     299.994760        0  
4             24.387087      16.351007        0  
...                 ...            ...      ...  
19811         14.928161      20.853466        0  
19812         12.614278      15.176401        0  
19813         27.504545      12.065808        0  
19814         24.900201      11.658888        0  
19815         20.267462     339.682405        0  

[19816 rows x 16 columns]

In [70]:
X = df[['body_part_name', 'sub_type_name', 'distance_to_goal', 'angle_to_goal', 'under_pressure', 'shot_first_time']] # pongo estas dos features nuevas - johan
y = df['outcome']


X = X.fillna(0)
X = pd.get_dummies(X, dtype=int) # right way to do it - johan

X

distance_to_goal  angle_to_goal  under_pressure  body_part_name_Head  \
0             18.600269      15.850859             0.0                    0   
1             15.352199      11.720028             0.0                    0   
2             11.346365      15.263642             1.0                    0   
3              6.258594     299.994760             0.0                    1   
4             24.387087      16.351007             0.0                    0   
...                 ...            ...             ...                  ...   
19811         14.928161      20.853466             0.0                    0   
19812         12.614278      15.176401             0.0                    0   
19813         27.504545      12.065808             0.0                    0   
19814         24.900201      11.658888             0.0                    0   
19815         20.267462     339.682405             0.0                    0   

       body_part_name_Left Foot  body_part_name_Other  \
0                             0                     0   
1                             0                     0   
2                             1                     0   
3                             0                     0   
4                             0                     0   
...                         ...                   ...   
19811                         0                     0   
19812                         0                     0   
19813                         0                     0   
19814                         1                     0   
19815                         0                     0   

       body_part_name_Right Foot  sub_type_name_Corner  \
0                              1                     0   
1                              1                     0   
2                              0                     0   
3                              0                     0   
4                              1                     0   
...                          ...                   ...   
19811                          1                     0   
19812                          1                     0   
19813                          1                     0   
19814                          0                     0   
19815                          1                     0   

       sub_type_name_Free Kick  sub_type_name_Open Play  \
0                            0                        1   
1                            0                        1   
2                            0                        1   
3                            0                        1   
4                            0                        1   
...                        ...                      ...   
19811                        0                        1   
19812                        0                        1   
19813                        0                        1   
19814                        0                        1   
19815                        0                        1   

       sub_type_name_Penalty  shot_first_time_0  shot_first_time_True  
0                          0                  1                     0  
1                          0                  1                     0  
2                          0                  0                     1  
3                          0                  1                     0  
4                          0                  1                     0  
...                      ...                ...                   ...  
19811                      0                  1                     0  
19812                      0                  1                     0  
19813                      0                  1                     0  
19814                      0                  1                     0  
19815                      0                  1                     0  

[19816 rows x 13 columns]

In [71]:
from sklearn.model_selection import train_test_split # hay q splitear antes de hacer scaling - johan
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=RANDOM_STATE)

In [72]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns)
X_test = pd.DataFrame(scaler.transform(X_test), columns=X_test.columns)


In [73]:
# We will try to see what accuracy we would get if we made a model which would always say that we didn't score
from sklearn.metrics import confusion_matrix, accuracy_score, log_loss  # Allegedly log loss might be good para medir la performance del model - johan

no_goals = np.zeros_like(y_test)
accuracy_score(y_test, no_goals)

0.9023011707710941

Therefore anything under 0.9023 accuracy underperforms our benchmark and should therefore be rejected

In [74]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

lr_clf = LogisticRegression(max_iter=200, random_state=RANDOM_STATE).fit(X_train, y_train)
y_pred = clf.predict(X_test)
lr_score = cross_val_score(lr_clf, X_test, y_test, cv=5)
lr_score.mean()

np.float64(0.9073475420195904)

In [75]:
confusion_matrix(y[y_test.index], y_pred)

array([[4459,   11],
       [ 437,   47]])

In [76]:
#Implementation of Naive Bayes
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
bys = gnb.fit(X_train, y_train)
#el parameter de priors lo dejo por defecto porque es solo si la data doesen't portray el mundo real
#el de var_smoothing tampoco lo toco porque por default se usa este valor para prevenir overfitting



In [77]:
y_pred_gnb = bys.predict(X_test)
bys_score = cross_val_score(bys, X_test, y_test, cv=5)
bys_score.mean()

np.float64(0.9081554189727751)

In [78]:
confusion_matrix(y_test, y_pred_gnb)

array([[4458,   12],
       [ 443,   41]])

In [79]:
#Implementation of Decision Tree
from sklearn.tree import DecisionTreeClassifier
treeclf = DecisionTreeClassifier(max_depth=5, random_state=RANDOM_STATE) # max_depth=25 es overfitting af - johan
treeclf.fit(X_train, y_train)
tree_score = cross_val_score(treeclf, X_test, y_test, cv=5)
tree_score.mean()


np.float64(0.9103756026460366)

In [80]:
confusion_matrix(y_test, treeclf.predict(X_test))

array([[4457,   13],
       [ 433,   51]])

In [92]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(n_estimators=100, random_state=RANDOM_STATE)
rf_clf.fit(X_train, y_train)

y_pred = rf_clf.predict(X_test)
rf_score = cross_val_score(rf_clf, X_test, y_test, cv=5)
rf_score.mean()

np.float64(0.906339071848658)

In [91]:
# The accuracy is suspiciously high
print(rf_clf.feature_importances_) # We check if there is something wrong with our features (possible data leak)
confusion_matrix(y_test, y_pred)

[0.46886712 0.45223588 0.01116319 0.00683717 0.00338359 0.00163257
 0.00489235 0.00064996 0.00457718 0.01064122 0.02908333 0.00299807
 0.00303836]


array([[4409,   61],
       [ 115,  369]])

In [83]:
#Implementation Ensamble Learing (hard voting)
from sklearn.ensemble import VotingClassifier
clf_hard_voting = VotingClassifier(
    estimators=[('lr', lr_clf), ('dt', treeclf), ('bys', bys), ('rf', rf_clf)], # As they have all surpassed 0.9023 we can use them all
    voting = 'hard')
clf_hard_voting.fit(X_train, y_train)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(max_iter=200,
                                                 random_state=67)),
                             ('dt',
                              DecisionTreeClassifier(max_depth=5,
                                                     random_state=67)),
                             ('bys', GaussianNB()),
                             ('rf', RandomForestClassifier(random_state=67))])

In [93]:
pred_hardvoting = clf_hard_voting.predict(X_test)
hardvoting_score = cross_val_score(clf_hard_voting, X_test, y_test, cv=5)
hardvoting_score.mean()

np.float64(0.9079533987707551)

In [85]:
from typing import List

def compare_classifiers_accuracies(clfs: List[object], X_train, X_test, y_train, y_test):
    for clf in clfs:
        clf.fit(X_train, y_train)
        y_pred = clf.predict(X_test)
        print(f"{clf.__class__.__name__}:", accuracy_score(y_test, y_pred))

compare_classifiers_accuracies([clf, treeclf, bys, rf_clf, clf_hard_voting], X_train, X_test, y_train, y_test)

LogisticRegression: 0.9095680258377069
DecisionTreeClassifier: 0.9099717400080742
GaussianNB: 0.9081550262414211
RandomForestClassifier: 0.9644731530076706
VotingClassifier: 0.9089624545821559


In [86]:
#Implementation Ensamble Learing (soft voting)
clf_soft_voting = VotingClassifier(
    estimators=[('lr', clf), ('dt', treeclf), ('bys', bys), ('rf', rf_clf)],
    voting = 'soft') # he quitado las weights pq resulta en overfitting - johan
clf_soft_voting.fit(X_train, y_train)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(max_iter=200,
                                                 random_state=67)),
                             ('dt',
                              DecisionTreeClassifier(max_depth=5,
                                                     random_state=67)),
                             ('bys', GaussianNB()),
                             ('rf', RandomForestClassifier(random_state=67))],
                 voting='soft')

In [94]:
pred_softvoting = clf_soft_voting.predict(X_test)
softvoting_score = cross_val_score(clf_soft_voting, X_test, y_test, cv=5)
softvoting_score.mean()

np.float64(0.9103753987911405)

In [88]:
compare_classifiers_accuracies([clf, treeclf, bys, rf_clf, clf_hard_voting, clf_soft_voting], X_train, X_test, y_train, y_test)

LogisticRegression: 0.9095680258377069
DecisionTreeClassifier: 0.9099717400080742
GaussianNB: 0.9081550262414211
RandomForestClassifier: 0.9644731530076706
VotingClassifier: 0.9089624545821559
VotingClassifier: 0.9103754541784417


In [89]:
# It looks like something is contaminating our soft voting (probably naive bayes), we will try without it 
clf_soft_voting_2 = VotingClassifier(
    estimators=[('lr', clf), ('dt', treeclf), ('rf', rf_clf)],
    voting = 'soft') 
clf_soft_voting_2.fit(X_train, y_train)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(max_iter=200,
                                                 random_state=67)),
                             ('dt',
                              DecisionTreeClassifier(max_depth=5,
                                                     random_state=67)),
                             ('rf', RandomForestClassifier(random_state=67))],
                 voting='soft')

In [95]:
pred_softvoting_2 = clf_soft_voting_2.predict(X_test)
softvoting_2_score = cross_val_score(clf_soft_voting_2, X_test, y_test, cv=5)
softvoting_2_score.mean()

np.float64(0.910779439195181)