In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_pickle("./filtered_data.pkl")  
df.shape

(19816, 15)

In [5]:
df

outcome_name  under_pressure sub_type_name body_part_name  \
0          Blocked             NaN     Open Play     Right Foot   
1          Blocked             NaN     Open Play     Right Foot   
2            Off T             1.0     Open Play      Left Foot   
3            Off T             NaN     Open Play           Head   
4          Wayward             NaN     Open Play     Right Foot   
...            ...             ...           ...            ...   
19811        Saved             NaN     Open Play     Right Foot   
19812        Saved             NaN     Open Play     Right Foot   
19813      Blocked             NaN     Open Play     Right Foot   
19814        Saved             NaN     Open Play      Left Foot   
19815        Saved             NaN     Open Play     Right Foot   

      shot_first_time      x     y pass_deflected shot_one_on_one  \
0                 NaN  107.1  26.6            NaN             NaN   
1                 NaN  113.7  54.0            NaN             NaN   
2                True  115.7  50.5            NaN             NaN   
3                 NaN  113.9  38.6            NaN             NaN   
4                 NaN   96.7  47.2            NaN             NaN   
...               ...    ...   ...            ...             ...   
19811             NaN  109.1  29.8            NaN             NaN   
19812             NaN  114.6  51.4            NaN            True   
19813             NaN   98.3  56.9            NaN             NaN   
19814             NaN  102.9  58.1            NaN             NaN   
19815             NaN   99.9  37.4            NaN             NaN   

      play_pattern_name type_name goalkeeper_position_name technique_name  \
0          Regular Play      Shot                      NaN         Normal   
1          Regular Play      Shot                      NaN         Normal   
2          Regular Play      Shot                      NaN  Overhead Kick   
3         From Throw In      Shot                      NaN         Normal   
4        From Free Kick      Shot                      NaN    Half Volley   
...                 ...       ...                      ...            ...   
19811      Regular Play      Shot                      NaN         Normal   
19812      From Counter      Shot                      NaN         Normal   
19813     From Throw In      Shot                      NaN         Normal   
19814      Regular Play      Shot                      NaN         Normal   
19815      Regular Play      Shot                      NaN         Normal   

       distance_to_goal  angle_to_goal  
0             18.600269      15.850859  
1             15.352199      11.720028  
2             11.346365      15.263642  
3              6.258594     299.994760  
4             24.387087      16.351007  
...                 ...            ...  
19811         14.928161      20.853466  
19812         12.614278      15.176401  
19813         27.504545      12.065808  
19814         24.900201      11.658888  
19815         20.267462     339.682405  

[19816 rows x 15 columns]

In [6]:
df["outcome"] = (df["outcome_name"] == "Goal").astype(int)
df

outcome_name  under_pressure sub_type_name body_part_name  \
0          Blocked             NaN     Open Play     Right Foot   
1          Blocked             NaN     Open Play     Right Foot   
2            Off T             1.0     Open Play      Left Foot   
3            Off T             NaN     Open Play           Head   
4          Wayward             NaN     Open Play     Right Foot   
...            ...             ...           ...            ...   
19811        Saved             NaN     Open Play     Right Foot   
19812        Saved             NaN     Open Play     Right Foot   
19813      Blocked             NaN     Open Play     Right Foot   
19814        Saved             NaN     Open Play      Left Foot   
19815        Saved             NaN     Open Play     Right Foot   

      shot_first_time      x     y pass_deflected shot_one_on_one  \
0                 NaN  107.1  26.6            NaN             NaN   
1                 NaN  113.7  54.0            NaN             NaN   
2                True  115.7  50.5            NaN             NaN   
3                 NaN  113.9  38.6            NaN             NaN   
4                 NaN   96.7  47.2            NaN             NaN   
...               ...    ...   ...            ...             ...   
19811             NaN  109.1  29.8            NaN             NaN   
19812             NaN  114.6  51.4            NaN            True   
19813             NaN   98.3  56.9            NaN             NaN   
19814             NaN  102.9  58.1            NaN             NaN   
19815             NaN   99.9  37.4            NaN             NaN   

      play_pattern_name type_name goalkeeper_position_name technique_name  \
0          Regular Play      Shot                      NaN         Normal   
1          Regular Play      Shot                      NaN         Normal   
2          Regular Play      Shot                      NaN  Overhead Kick   
3         From Throw In      Shot                      NaN         Normal   
4        From Free Kick      Shot                      NaN    Half Volley   
...                 ...       ...                      ...            ...   
19811      Regular Play      Shot                      NaN         Normal   
19812      From Counter      Shot                      NaN         Normal   
19813     From Throw In      Shot                      NaN         Normal   
19814      Regular Play      Shot                      NaN         Normal   
19815      Regular Play      Shot                      NaN         Normal   

       distance_to_goal  angle_to_goal  outcome  
0             18.600269      15.850859        0  
1             15.352199      11.720028        0  
2             11.346365      15.263642        0  
3              6.258594     299.994760        0  
4             24.387087      16.351007        0  
...                 ...            ...      ...  
19811         14.928161      20.853466        0  
19812         12.614278      15.176401        0  
19813         27.504545      12.065808        0  
19814         24.900201      11.658888        0  
19815         20.267462     339.682405        0  

[19816 rows x 16 columns]

In [7]:

X = df[['body_part_name', 'sub_type_name', 'distance_to_goal', 'angle_to_goal']]
y = df['outcome']
X

body_part_name sub_type_name  distance_to_goal  angle_to_goal
0         Right Foot     Open Play         18.600269      15.850859
1         Right Foot     Open Play         15.352199      11.720028
2          Left Foot     Open Play         11.346365      15.263642
3               Head     Open Play          6.258594     299.994760
4         Right Foot     Open Play         24.387087      16.351007
...              ...           ...               ...            ...
19811     Right Foot     Open Play         14.928161      20.853466
19812     Right Foot     Open Play         12.614278      15.176401
19813     Right Foot     Open Play         27.504545      12.065808
19814      Left Foot     Open Play         24.900201      11.658888
19815     Right Foot     Open Play         20.267462     339.682405

[19816 rows x 4 columns]

In [8]:
X['body_part_name'], _ = pd.factorize(X['body_part_name'])  # Turn labels into classes
X['sub_type_name'], _ = pd.factorize(X['sub_type_name'])

C:\Users\Usuario\AppData\Local\Temp\ipykernel_1020\1906990171.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['body_part_name'], _ = pd.factorize(X['body_part_name'])  # Turn labels into classes
C:\Users\Usuario\AppData\Local\Temp\ipykernel_1020\1906990171.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['sub_type_name'], _ = pd.factorize(X['sub_type_name'])


In [9]:
### Standardization and blah blah blah

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
X_scaled

body_part_name  sub_type_name  distance_to_goal  angle_to_goal
0           -0.826929      -0.223439         -0.056890      -0.640502
1           -0.826929      -0.223439         -0.448657      -0.670442
2            0.498190      -0.223439         -0.931823      -0.644758
3            1.823310      -0.223439         -1.545487       1.418982
4           -0.826929      -0.223439          0.641090      -0.636876
...               ...            ...               ...            ...
19811       -0.826929      -0.223439         -0.499803      -0.604242
19812       -0.826929      -0.223439         -0.778893      -0.645390
19813       -0.826929      -0.223439          1.017104      -0.667936
19814        0.498190      -0.223439          0.702979      -0.670885
19815       -0.826929      -0.223439          0.144199       1.706639

[19816 rows x 4 columns]

In [10]:
# Remove outliers abs(std) > 3

X_cleaned = X_scaled[(X_scaled.abs() <= 3).all(axis=1)]
y_cleaned = y[(X_scaled.abs() <= 3).all(axis=1)]
X_cleaned

body_part_name  sub_type_name  distance_to_goal  angle_to_goal
0           -0.826929      -0.223439         -0.056890      -0.640502
1           -0.826929      -0.223439         -0.448657      -0.670442
2            0.498190      -0.223439         -0.931823      -0.644758
3            1.823310      -0.223439         -1.545487       1.418982
4           -0.826929      -0.223439          0.641090      -0.636876
...               ...            ...               ...            ...
19811       -0.826929      -0.223439         -0.499803      -0.604242
19812       -0.826929      -0.223439         -0.778893      -0.645390
19813       -0.826929      -0.223439          1.017104      -0.667936
19814        0.498190      -0.223439          0.702979      -0.670885
19815       -0.826929      -0.223439          0.144199       1.706639

[18926 rows x 4 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_cleaned, y_cleaned)

In [12]:
#Implementation of PCA
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
X_pca = pca.fit_transform(X_train)
X_pca_test = pca.transform(X_test)

In [13]:
#Implementation of Logistic Regression
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(max_iter=200).fit(X_train, y_train)
y_pred = clf.predict(X_test)
clf.score(X_test, y_test)

0.9030008453085376

In [14]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y[y_test.index], y_pred)

array([[4242,   10],
       [ 449,   31]])

In [15]:
#Implementation of Naive Bayes
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
bys = gnb.fit(X_train, y_train)
#el parameter de priors lo dejo por defecto porque es solo si la data doesen't portray el mundo real
#el de var_smoothing tampoco lo toco porque por default se usa este valor para prevenir overfitting

In [16]:
y_pred_gnb = bys.predict(X_test)
bys.score(X_test, y_test)

0.9027895181741336

In [17]:
confusion_matrix(y_test, y_pred_gnb)

array([[4244,    8],
       [ 452,   28]])

In [43]:
#Implementation of Decision Tree
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
treeclf = DecisionTreeClassifier(max_depth=25)
treeclf.fit(X_train, y_train)


DecisionTreeClassifier(max_depth=25)

In [46]:
#treeplot = tree.plot_tree(treeclf)

In [52]:
from sklearn.metrics import accuracy_score
y_tree_predict = treeclf.predict(X_test)
acctpred = accuracy_score(y_test, y_tree_predict)
acctpred

0.9425190194420964

In [53]:
confusion_matrix(y_test, y_tree_predict)

array([[4145,  107],
       [ 165,  315]])

In [ ]:
#Implementation Ensamble Learing 
